server:
    port: 7090
    tomcat:
        accesslog:
            directory: /logs/${spring.application.name}
spring:
    application:
        name: msg-service
    datasource:
        druid:
            driver-class-name: com.mysql.jdbc.Driver
#            url: jdbc:mysql://121.5.231.18:8001/db1?useUnicode=true&useSSL=false&characterEncoding=UTF-8
#            username: root
#            password: 123456
            webStatFilter:
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: admin
                login-password: admin
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 5000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
        type: com.alibaba.druid.pool.DruidDataSource
        ds:
            # 主库数据源，默认 master 不能变
            master:
                url: jdbc:mysql://127.0.0.1/db2?useUnicode=true&useSSL=false&characterEncoding=UTF-8
                username: root
                password: 123456
            # 从库数据源
            slave:
                url: jdbc:mysql://121.5.231.18:8001/db1?useUnicode=true&useSSL=false&characterEncoding=UTF-8
                username: root
                password: 123456
        # 初始连接数
        initialSize: 5
        # 最小连接池数量
        minIdle: 10
        # 最大连接池数量
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 配置一个连接在池中最大生存的时间，单位是毫秒
        maxEvictableIdleTimeMillis: 900000
        # 配置检测连接是否有效
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
    redis:
        host: 121.5.231.18
        port: 8002
rocketmq:
    name-server: 121.5.231.18:9876
    producer:
        group: testPro
        send-message-timeout: 3000
        retry-times-when-send-async-failed: 2
        max-message-size: 4194304
mybatis:
    type-aliases-package: com.msg_service.msg.model
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mapperxml/*Mapper.xml
wx:
    appid: wx2343f2de052e8191
    tokenurl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
    appsecret: f791cf1e68db99e27977b653d01d72b3
    msgurl: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=%s